default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>
  host: <%= ENV["PHARMA_DATABASE_HOST"] %>
  username: <%= ENV["PHARMA_DATABASE_USER"] %>
  password: <%= ENV["PHARMA_DATABASE_PASSWORD"] %>

development:
  <<: *default
  database: pharma_dashboard_development

test:
  <<: *default
  database: pharma_dashboard_test

production:
  url: <%= ENV["DATABASE_URL"] %>
