# config/database.yml
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: pharmatransport_db_development

test:
  <<: *default
  database: pharmatransport_db_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>

# Solid Stack (Phase 14 GPS WebSockets + Cache)
cable:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>

cache:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>

queue:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
