require "test_helper"

class GenerateDeliveryPacketJobTest < ActiveJob::TestCase
  setup do
    @organization = Organization.create!(name: "Acme Pharma")
    @vehicle = Vehicle.create!(name: "Truck 1", organization: @organization)
    @recorder = User.create!(email: "dispatch@example.com", password: "password123!", organization: @organization, role: "dispatcher")
    @batch = Batch.create!(lot_number: "LOT-1", temperature_celsius: 5, vehicle: @vehicle, organization: @organization)
  end

  # A real 1x1 PNG -- PdfChainOfCustodyGenerator actually embeds this in the
  # packet, so it has to decode.
  TINY_PNG = "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNk+A8AAQUBAScY42YAAAAASUVORK5CYII="

  def delivery_log
    @batch.custody_logs.create!(
      action_type: "delivered", handler_name: "Jane Doe", location: "Phoenix, AZ",
      signature_data: { "image" => TINY_PNG, "signer_name" => "Jane Doe" }
    )
  end

  test "generates the batch's first Compliance Packet" do
    log = delivery_log

    assert_difference -> { @batch.compliance_reports.count }, 1 do
      GenerateDeliveryPacketJob.perform_now(log.id, @recorder.id)
    end

    report = @batch.compliance_reports.last
    assert_equal 1, report.version
    assert_equal @recorder, report.generated_by
    assert_equal "compliance_report_generated", AuditLog.last.event
    assert_equal "delivery", AuditLog.last.data["trigger"]
  end

  test "is idempotent -- a second run does nothing" do
    log = delivery_log
    GenerateDeliveryPacketJob.perform_now(log.id, @recorder.id)

    assert_no_difference -> { @batch.compliance_reports.count } do
      GenerateDeliveryPacketJob.perform_now(log.id, @recorder.id)
    end
  end

  test "does nothing if a packet was already generated by hand after the delivery" do
    log = delivery_log
    ComplianceReportGenerator.new(@batch).generate!(generated_by: @recorder)

    assert_no_difference -> { @batch.compliance_reports.count } do
      GenerateDeliveryPacketJob.perform_now(log.id, @recorder.id)
    end
  end

  test "over the monthly cap it skips generation and records why" do
    log = delivery_log
    ComplianceReportQuota::FREE_MONTHLY_LIMIT.times do
      other = Batch.create!(lot_number: "LOT-x#{_1}", vehicle: @vehicle, organization: @organization)
      ComplianceReportGenerator.new(other).generate!(generated_by: @recorder)
    end

    assert_no_difference -> { @batch.compliance_reports.count } do
      GenerateDeliveryPacketJob.perform_now(log.id, @recorder.id)
    end
    assert_equal "compliance_packet_autogen_skipped", AuditLog.last.event
    assert_equal "monthly_allowance_reached", AuditLog.last.data["reason"]
  end

  test "spends a purchased credit when over the cap but one is available" do
    log = delivery_log
    ComplianceReportQuota::FREE_MONTHLY_LIMIT.times do
      other = Batch.create!(lot_number: "LOT-y#{_1}", vehicle: @vehicle, organization: @organization)
      ComplianceReportGenerator.new(other).generate!(generated_by: @recorder)
    end
    credit = ReportCredit.grant!(organization: @organization, stripe_checkout_session_id: "cs_1")

    assert_difference -> { @batch.compliance_reports.count }, 1 do
      GenerateDeliveryPacketJob.perform_now(log.id, @recorder.id)
    end
    assert_not_nil credit.reload.consumed_at
  end

  test "no-op for a non-delivery custody event" do
    log = @batch.custody_logs.create!(action_type: "handoff", handler_name: "J", location: "L")

    assert_no_difference -> { ComplianceReport.count } do
      GenerateDeliveryPacketJob.perform_now(log.id, @recorder.id)
    end
  end

  test "no-op if the custody log or user has since been deleted" do
    log = delivery_log
    id = log.id
    log.destroy

    assert_no_difference -> { ComplianceReport.count } do
      GenerateDeliveryPacketJob.perform_now(id, @recorder.id)
    end
  end
end
